# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os 
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "C:/Users/Administrator/AppData/Local/Programs/Python/Python312/Lib/site-packages/PyQt5/Qt5/plugins/platforms"

class Ui_CaesarCipher(object):
    def setupUi(self, CaesarCipher):
        CaesarCipher.setObjectName("CaesarCipher")
        CaesarCipher.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(CaesarCipher)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_Caesar = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Caesar.setGeometry(QtCore.QRect(250, 10, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Caesar.setFont(font)
        self.lbl_Caesar.setObjectName("lbl_Caesar")
        self.lbl_plaintext = QtWidgets.QLabel(self.centralwidget)
        self.lbl_plaintext.setGeometry(QtCore.QRect(50, 110, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_plaintext.setFont(font)
        self.lbl_plaintext.setObjectName("lbl_plaintext")
        self.lbl_key = QtWidgets.QLabel(self.centralwidget)
        self.lbl_key.setGeometry(QtCore.QRect(50, 220, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_key.setFont(font)
        self.lbl_key.setObjectName("lbl_key")
        self.lbl_ciphertext = QtWidgets.QLabel(self.centralwidget)
        self.lbl_ciphertext.setGeometry(QtCore.QRect(50, 340, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_ciphertext.setFont(font)
        self.lbl_ciphertext.setObjectName("lbl_ciphertext")
        self.txt_PlainText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_PlainText.setGeometry(QtCore.QRect(230, 80, 381, 71))
        self.txt_PlainText.setObjectName("txt_PlainText")
        self.txt_Key = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Key.setGeometry(QtCore.QRect(230, 220, 381, 41))
        self.txt_Key.setObjectName("txt_Key")
        self.txt_CipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_CipherText.setGeometry(QtCore.QRect(230, 330, 381, 71))
        self.txt_CipherText.setObjectName("txt_CipherText")
        self.btn_Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Encrypt.setGeometry(QtCore.QRect(170, 450, 75, 23))
        self.btn_Encrypt.setObjectName("btn_Encrypt")
        self.btn_Decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Decrypt.setGeometry(QtCore.QRect(450, 450, 75, 23))
        self.btn_Decrypt.setObjectName("btn_Decrypt")
        CaesarCipher.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CaesarCipher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        CaesarCipher.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CaesarCipher)
        self.statusbar.setObjectName("statusbar")
        CaesarCipher.setStatusBar(self.statusbar)

        self.retranslateUi(CaesarCipher)
        QtCore.QMetaObject.connectSlotsByName(CaesarCipher)

    def retranslateUi(self, CaesarCipher):
        _translate = QtCore.QCoreApplication.translate
        CaesarCipher.setWindowTitle(_translate("CaesarCipher", "CaesarCipher"))
        self.lbl_Caesar.setText(_translate("CaesarCipher", "CAESAR CIPHER"))
        self.lbl_plaintext.setText(_translate("CaesarCipher", "Plain Text:"))
        self.lbl_key.setText(_translate("CaesarCipher", "Key:"))
        self.lbl_ciphertext.setText(_translate("CaesarCipher", "Cipher Text:"))
        self.btn_Encrypt.setText(_translate("CaesarCipher", "Encrypt"))
        self.btn_Decrypt.setText(_translate("CaesarCipher", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CaesarCipher = QtWidgets.QMainWindow()
    ui = Ui_CaesarCipher()
    ui.setupUi(CaesarCipher)
    CaesarCipher.show()
    sys.exit(app.exec_())
