# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ECCCipher(object):
    def setupUi(self, ECCCipher):
        ECCCipher.setObjectName("ECCCipher")
        ECCCipher.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ECCCipher)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 20, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 150, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 250, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txt_Information = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Information.setGeometry(QtCore.QRect(240, 120, 391, 71))
        self.txt_Information.setObjectName("txt_Information")
        self.txt_Signature = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Signature.setGeometry(QtCore.QRect(240, 240, 391, 71))
        self.txt_Signature.setObjectName("txt_Signature")
        self.btn_Sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Sign.setGeometry(QtCore.QRect(220, 390, 75, 23))
        self.btn_Sign.setObjectName("btn_Sign")
        self.btn_Verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Verify.setGeometry(QtCore.QRect(470, 390, 75, 23))
        self.btn_Verify.setObjectName("btn_Verify")
        self.btn_GenerateKeys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_GenerateKeys.setGeometry(QtCore.QRect(490, 40, 91, 31))
        self.btn_GenerateKeys.setObjectName("btn_GenerateKeys")
        ECCCipher.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ECCCipher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        ECCCipher.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ECCCipher)
        self.statusbar.setObjectName("statusbar")
        ECCCipher.setStatusBar(self.statusbar)

        self.retranslateUi(ECCCipher)
        QtCore.QMetaObject.connectSlotsByName(ECCCipher)

    def retranslateUi(self, ECCCipher):
        _translate = QtCore.QCoreApplication.translate
        ECCCipher.setWindowTitle(_translate("ECCCipher", "ECCCIPHER"))
        self.label.setText(_translate("ECCCipher", "ECC CIPHER"))
        self.label_2.setText(_translate("ECCCipher", "Information:"))
        self.label_3.setText(_translate("ECCCipher", "Signature:"))
        self.btn_Sign.setText(_translate("ECCCipher", "Sign"))
        self.btn_Verify.setText(_translate("ECCCipher", "Verify"))
        self.btn_GenerateKeys.setText(_translate("ECCCipher", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ECCCipher = QtWidgets.QMainWindow()
    ui = Ui_ECCCipher()
    ui.setupUi(ECCCipher)
    ECCCipher.show()
    sys.exit(app.exec_())
