# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/railfence.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RailFenceCipher(object):
    def setupUi(self, RailFenceCipher):
        RailFenceCipher.setObjectName("RailFenceCipher")
        RailFenceCipher.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(RailFenceCipher)
        self.centralwidget.setObjectName("centralwidget")
        self.lable3 = QtWidgets.QLabel(self.centralwidget)
        self.lable3.setGeometry(QtCore.QRect(60, 240, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lable3.setFont(font)
        self.lable3.setObjectName("lable3")
        self.btn_Decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Decrypt.setGeometry(QtCore.QRect(460, 470, 75, 23))
        self.btn_Decrypt.setObjectName("btn_Decrypt")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(60, 130, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.Lable1 = QtWidgets.QLabel(self.centralwidget)
        self.Lable1.setGeometry(QtCore.QRect(240, 10, 391, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Lable1.setFont(font)
        self.Lable1.setObjectName("Lable1")
        self.txt_Key = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Key.setGeometry(QtCore.QRect(240, 240, 381, 41))
        self.txt_Key.setObjectName("txt_Key")
        self.txt_PlainText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_PlainText.setGeometry(QtCore.QRect(240, 100, 381, 71))
        self.txt_PlainText.setObjectName("txt_PlainText")
        self.btn_Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Encrypt.setGeometry(QtCore.QRect(180, 470, 75, 23))
        self.btn_Encrypt.setObjectName("btn_Encrypt")
        self.lable4 = QtWidgets.QLabel(self.centralwidget)
        self.lable4.setGeometry(QtCore.QRect(60, 360, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lable4.setFont(font)
        self.lable4.setObjectName("lable4")
        self.txt_CipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_CipherText.setGeometry(QtCore.QRect(240, 350, 381, 71))
        self.txt_CipherText.setObjectName("txt_CipherText")
        RailFenceCipher.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RailFenceCipher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        RailFenceCipher.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RailFenceCipher)
        self.statusbar.setObjectName("statusbar")
        RailFenceCipher.setStatusBar(self.statusbar)

        self.retranslateUi(RailFenceCipher)
        QtCore.QMetaObject.connectSlotsByName(RailFenceCipher)

    def retranslateUi(self, RailFenceCipher):
        _translate = QtCore.QCoreApplication.translate
        RailFenceCipher.setWindowTitle(_translate("RailFenceCipher", "RailFenceCipher"))
        self.lable3.setText(_translate("RailFenceCipher", "Key:"))
        self.btn_Decrypt.setText(_translate("RailFenceCipher", "Decrypt"))
        self.label2.setText(_translate("RailFenceCipher", "Plain Text:"))
        self.Lable1.setText(_translate("RailFenceCipher", "RAILFENCE CIPHER"))
        self.btn_Encrypt.setText(_translate("RailFenceCipher", "Encrypt"))
        self.lable4.setText(_translate("RailFenceCipher", "Cipher Text:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RailFenceCipher = QtWidgets.QMainWindow()
    ui = Ui_RailFenceCipher()
    ui.setupUi(RailFenceCipher)
    RailFenceCipher.show()
    sys.exit(app.exec_())
