# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/transposition.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TranspositionCipher(object):
    def setupUi(self, TranspositionCipher):
        TranspositionCipher.setObjectName("TranspositionCipher")
        TranspositionCipher.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(TranspositionCipher)
        self.centralwidget.setObjectName("centralwidget")
        self.Lable1 = QtWidgets.QLabel(self.centralwidget)
        self.Lable1.setGeometry(QtCore.QRect(200, 20, 491, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Lable1.setFont(font)
        self.Lable1.setObjectName("Lable1")
        self.txt_CipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_CipherText.setGeometry(QtCore.QRect(270, 370, 381, 71))
        self.txt_CipherText.setObjectName("txt_CipherText")
        self.txt_PlainText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_PlainText.setGeometry(QtCore.QRect(270, 120, 381, 71))
        self.txt_PlainText.setObjectName("txt_PlainText")
        self.btn_Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Encrypt.setGeometry(QtCore.QRect(210, 490, 75, 23))
        self.btn_Encrypt.setObjectName("btn_Encrypt")
        self.txt_Key = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Key.setGeometry(QtCore.QRect(270, 260, 381, 41))
        self.txt_Key.setObjectName("txt_Key")
        self.btn_Decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Decrypt.setGeometry(QtCore.QRect(490, 490, 75, 23))
        self.btn_Decrypt.setObjectName("btn_Decrypt")
        self.lable3 = QtWidgets.QLabel(self.centralwidget)
        self.lable3.setGeometry(QtCore.QRect(90, 260, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lable3.setFont(font)
        self.lable3.setObjectName("lable3")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(90, 150, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.lable4 = QtWidgets.QLabel(self.centralwidget)
        self.lable4.setGeometry(QtCore.QRect(90, 380, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lable4.setFont(font)
        self.lable4.setObjectName("lable4")
        TranspositionCipher.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TranspositionCipher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        TranspositionCipher.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TranspositionCipher)
        self.statusbar.setObjectName("statusbar")
        TranspositionCipher.setStatusBar(self.statusbar)

        self.retranslateUi(TranspositionCipher)
        QtCore.QMetaObject.connectSlotsByName(TranspositionCipher)

    def retranslateUi(self, TranspositionCipher):
        _translate = QtCore.QCoreApplication.translate
        TranspositionCipher.setWindowTitle(_translate("TranspositionCipher", "TranspositionCipher"))
        self.Lable1.setText(_translate("TranspositionCipher", "TRANSPOSITION CIPHER"))
        self.btn_Encrypt.setText(_translate("TranspositionCipher", "Encrypt"))
        self.btn_Decrypt.setText(_translate("TranspositionCipher", "Decrypt"))
        self.lable3.setText(_translate("TranspositionCipher", "Key:"))
        self.label2.setText(_translate("TranspositionCipher", "Plain Text:"))
        self.lable4.setText(_translate("TranspositionCipher", "Cipher Text:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TranspositionCipher = QtWidgets.QMainWindow()
    ui = Ui_TranspositionCipher()
    ui.setupUi(TranspositionCipher)
    TranspositionCipher.show()
    sys.exit(app.exec_())
